# Generated by Django 5.0.9 on 2025-02-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathcode',
            name='code',
            field=models.TextField(max_length=4096),
        ),
    ]
