# Generated by Django 5.0.14 on 2025-05-27 13:18

import dbfile.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppCode',
            fields=[
                ('code_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='May only contain alphanumeric and underscore, not start with an underscore, and not be a number', max_length=40, unique=True)),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DashApp',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(help_text='Application relative URL - APP_BASENAME', max_length=80, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Application Display Name', max_length=40, unique=True)),
                ('template', models.CharField(help_text='Django template path', max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=120, null=True)),
                ('graphic', models.ImageField(null=True, storage=dbfile.models.DatabaseFileStorage, upload_to='')),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DashAppCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.appcode')),
                ('dashapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.dashapp')),
            ],
            options={
                'unique_together': {('dashapp', 'appcode')},
            },
        ),
        migrations.CreateModel(
            name='DashAppGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=150)),
                ('dashapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.dashapp')),
            ],
            options={
                'unique_together': {('dashapp', 'group')},
            },
        ),
    ]
