# Generated by Django 5.0.14 on 2025-10-07 11:42

import dbfile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashapp',
            name='graphic',
            field=models.ImageField(blank=True, null=True, storage=dbfile.models.DatabaseFileStorage, upload_to=''),
        ),
    ]
