# Generated by Django 5.0.14 on 2025-10-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0002_alter_dashapp_graphic'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcode',
            name='alias',
            field=models.CharField(blank=True, help_text='May only contain alphanumeric and underscore, not start with an underscore, and not be a number', max_length=40, null=True),
        ),
    ]
