# Generated by Django 5.0.14 on 2025-10-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0003_appcode_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashapp',
            name='name',
            field=models.CharField(help_text='Application Display Name', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='dashapp',
            name='path',
            field=models.CharField(db_index=True, help_text='Application relative URL - APP_BASENAME', max_length=80, unique=True),
        ),
    ]
