# Generated by Django 5.0.14 on 2025-10-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0004_alter_dashapp_name_alter_dashapp_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashapp',
            name='name',
            field=models.CharField(help_text='Application Display Name', max_length=40),
        ),
    ]
