# Generated by Django 5.0.14 on 2025-10-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0005_alter_dashapp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcode',
            name='name',
            field=models.CharField(db_index=True, help_text='May only contain alphanumeric and underscore, not start with an underscore, and not be a number', max_length=60, unique=True),
        ),
    ]
